# Generated by Django 5.2.7 on 2025-10-15 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='health',
        ),
        migrations.RemoveField(
            model_name='character',
            name='mana',
        ),
        migrations.RemoveField(
            model_name='character',
            name='party',
        ),
        migrations.AddField(
            model_name='character',
            name='alignment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='bonds',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='char_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='flaws',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='ideals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='traits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='dungeon_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
