# Generated by Django 5.2.7 on 2025-10-15 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0002_remove_character_health_remove_character_mana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='character',
            name='background',
        ),
        migrations.RemoveField(
            model_name='character',
            name='bonds',
        ),
        migrations.RemoveField(
            model_name='character',
            name='char_class',
        ),
        migrations.RemoveField(
            model_name='character',
            name='flaws',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ideals',
        ),
        migrations.RemoveField(
            model_name='character',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='character',
            name='traits',
        ),
        migrations.AddField(
            model_name='character',
            name='class_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='health',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='mana',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='dungeon_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_owned_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='game_parties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dungeon_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('parties', models.ManyToManyField(blank=True, related_name='campaigns', to='game_characters.party')),
            ],
        ),
    ]
