# Generated by Django 5.2.7 on 2025-10-24 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0004_partyinvitation_partymembercharacter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_characters.character')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_characters.party')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('party', 'player')},
            },
        ),
        migrations.DeleteModel(
            name='PartyMemberCharacter',
        ),
    ]
