# Generated by Django 5.2.7 on 2025-10-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_characters', '0005_partycharacter_delete_partymembercharacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(blank=True, default=1, max_length=100),
        ),
    ]
