# Generated by Django 5.2.7 on 2025-10-12 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterlocal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='characterlocal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterlocal',
            name='health',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='characterlocal',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='characterlocal',
            name='mana',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='characterlocal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characterlocal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='characterlocal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='characterlocal',
            name='sheet_row',
        ),
    ]
